metrotranscom/doorway-infra

bloom-instance/vpc.tf

This CL, with #20, resolves #7
test plan:
`terraform plan` also adds a igw and the vpc remains the same (did not run `terraform apply` after #20, so it makes sense that it is still there as well)

feat: add IGW

---

.github/workflows/check-format.yml
.github/workflows/lint.yml
.github/workflows/plan.yml
bloom-instance/.tflint.hcl
bloom-instance/main.tf
bloom-instance/vars.tf

Addresses #30
This CL adds 3 new GitHub workflows (but only 2 are enabled)
* A hook to run linting (https://github.com/terraform-linters/tflint) which checks for unused variables, etc.
* A hook to run terraform fmt (https://github.com/dflook/terraform-github-actions/tree/main/terraform-fmt-check) and fail if files are not properly formatted
* A hook that I commented out to show the output of `terraform plan`. This seems super useful but is not related to formatting and is probably more CI/CD related vs. just enforcing formatting. Happy to just delete the file if we don't think we'll use this at all. 
Note I will squash merge given that my commit messages are... creative.

feat: add lint and formatting commit hooks

---

bloom-instance/main.tf
bloom-instance/services/partner-site/iam.tf
bloom-instance/services/partner-site/inputs.tf
bloom-instance/services/partner-site/locals.tf
bloom-instance/services/partner-site/outputs.tf
bloom-instance/services/partner-site/service.tf
bloom-instance/tfvars.template
bloom-instance/vars.tf

The partner site module is virtually identical to the public site, although it's expected that these will deviate somewhat more over time.
Resolves #46 
[plan.txt](https://github.com/metrotranscom/doorway-infra/files/10961588/plan.txt)

add partner site

---

setup/ecr/inputs.tf
setup/ecr/outputs.tf
setup/ecr/policy.tf
setup/ecr/repo.tf
setup/main.tf
setup/outputs.tf
setup/tfvars.template
setup/vars.tf

The ECR repo needs a policy to tell it what sort of access is allowed.  I added statements allowing CodeBuild, ECS, and users in the account where resources will be deployed.  I also moved the ECR config into a module and modified the tfvars template to create a separate repo for each of the 3 services to minimize the chance of clobbering one image with another.
Fixes #63 
[plan.txt](https://github.com/metrotranscom/doorway-infra/files/10994922/plan.txt)

add ecr policy

---

bloom-instance/cert/inputs.tf
bloom-instance/cert/main.tf
bloom-instance/cert/outputs.tf
bloom-instance/certs.tf
bloom-instance/dns/record/outputs.tf
bloom-instance/dns/zone-resolver/inputs.tf
bloom-instance/dns/zone-resolver/main.tf
bloom-instance/dns/zone-resolver/outputs.tf
bloom-instance/outputs.tf
bloom-instance/tfvars.template
bloom-instance/vars.tf

This PR adds a cert module and a related var that instructs which certs to create.  It uses a re-added zone-resolver module to determine which DNS zone to use for automatically adding DNS validation records.  Certs are currently not being assigned to any resources, but the cert var uses a map so that other components (such as the alb module) can specify which certs to use via alias values since they won't know the ARN until apply-time.
Resolves #75

Add cert module

---

bloom-instance/ecs/service/ecs.tf

resolving an error when building the ci/cd pipeline
```
Error: Error creating CodeDeploy deployment group: InvalidECSServiceException: Deployment group's ECS service must be configured for a CODE_DEPLOY deployment controller.
```

ci: use CodeDeploy

---

bloom-instance/s3.tf

The bucket policy that was added in a previous PR (#93) can't actually be applied due to additional layers of protection added by AWS.  This PR disables those protections to prevent the `Access Denied` error that would occur otherwise.
[plan.txt](https://github.com/metrotranscom/doorway-infra/files/11357696/plan.txt)

fix: add aws_s3_public_access_block for public uploads

---

app-codepipeline/codepipeline.tf

This is required, since we're not yet building in parallel.

ci: increase build timeout

---

bloom-instance/main.tf
bloom-instance/s3.tf

This PR updates the names of the S3 buckets to include both the project ID and the workspace.  Before, all buckets had a name like `doorway-public-uploads...` regardless of whether they were in dev or a personal workspace.  This is intended to make it easier to tell them apart.

fix: update bucket names with name_prefix

---

bloom-instance/alb/listener/outputs.tf
bloom-instance/ecs/service/inputs.tf
bloom-instance/ecs/service/locals.tf
bloom-instance/ecs/service/outputs.tf
bloom-instance/outputs.tf
bloom-instance/service/backend/inputs.tf
bloom-instance/service/backend/locals.tf
bloom-instance/service/backend/outputs.tf
bloom-instance/service/inputs.tf
bloom-instance/service/outputs.tf
bloom-instance/service/partner-site/outputs.tf
bloom-instance/service/public-site/outputs.tf
bloom-instance/services.tf

Each of the services needs to know where to find at least one of the others.  This was previously hardcoded, but needs to be replaced with something more flexible.  This PR, in conjunction with [the corresponding config PR](https://github.com/metrotranscom/doorway-config/pull/16), adds the ability to specify which URLs to provide in the form of two extra properties attached to the root `backend_api` var.
In addition, it also adds some functionality for exporting URLs from services so they can be passed directly even if they were unknown prior to deployment.
[plan.txt](https://github.com/metrotranscom/doorway-infra/files/11556669/plan.txt)

fix: replace hardcoded urls with generated values

---

bloom-instance/db/outputs.tf
bloom-instance/service/backend/inputs.tf

Now that the DB password is stored in a secret, we don't need to output it from the db module.  This has no change on the deployment

fix: remove password from db outputs

---

bloom-instance/db/aurora.tf
bloom-instance/db/rds.tf

AWS will periodically update running RDS instances to update them to a new minor version.  When terraform sees that the `engine_version` is different than what is specified in the tfvars file on the next `plan`/`apply`, it attempts to roll it back to the initially requested version, undoing the upgrades.  This can cause a lot of thrashing as RDS and terraform continue to go back and forth applying and then undoing updates, which is undesirable.
This PR updates the db module to tell terraform to ignore any changes to `engine_version` when trying to determine which changes need to be made.

fix: ignore changes to db engine_version

---

infra-pipeline/main.tf
infra-pipeline/pipeline/iam.tf
infra-pipeline/pipeline/inputs.tf
infra-pipeline/pipeline/main.tf
infra-pipeline/pipeline/notification/rule/inputs.tf
infra-pipeline/pipeline/notification/rule/main.tf
infra-pipeline/pipeline/notification/rule/pipeline/inputs.tf
infra-pipeline/pipeline/notification/rule/pipeline/main.tf
infra-pipeline/pipeline/notification/topic/inputs.tf
infra-pipeline/pipeline/notification/topic/main.tf
infra-pipeline/pipeline/notification/topic/outputs.tf
infra-pipeline/tfvars.template
infra-pipeline/vars.tf

This PR adds support for defining pipeline notifications.  You can create notification topics, automatically subscribe emails to them, and filter which pipeline events trigger the notifications.  It also makes a few small unrelated changes like adding a name var to the pipeline object and changing the approval config to use the notification topics rather than its own thing.
The tfvar file used for the live deployment is available here: https://github.com/metrotranscom/doorway-config/blob/test/chriscasto/infra-pipeline/chriscasto.tfvars

feat: add pipeline notifications

---

bloom-instance/alb.tf
bloom-instance/cronjobs.tf
bloom-instance/db.tf
bloom-instance/logging.tf
bloom-instance/main.tf
bloom-instance/network.tf
bloom-instance/services.tf
bloom-instance/tfvars.template
bloom-instance/vars.tf

This PR is primarily intended to create a new tag named `ProjectID` that permissions can be tied to, since using the current `Project` tag, which can be easily changed, has proven problematic.  As we've built more and more templates in different terraform projects, it became apparent that some of the var names used initially did not represent the intended use very well.  Since I picked out most of the names, that's on me.  In addition to renaming the `name_prefix var to `project_id`, this PR incorporates the following additional changes:
- Change `sdlc_stage` to `environment`
- Update environment validation to be less prescriptive
- Change `team_name` to `owner`
- Change `Team` tag to `Owner`
- Update owner validation to permit email addresses
- Update top-level resources to use …

refactor: normalize bloom infra var names

---

bloom-instance/ecs/service/ecs.tf
bloom-instance/ecs/service/inputs.tf
bloom-instance/ecs/service/locals.tf
bloom-instance/ecs/service/scaling.tf

This PR adds an autoscaling configuration option to the services running on ECS.  Adding this to the backend service:
```
scaling = {
min : 1
max : 5
metrics = {
cpu : {
name : "ECSServiceAverageCPUUtilization"
target : 80
}
}
}
```
Generates this output:
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "aws_appautoscaling_policy" "ecs_policy" {
+ alarm_arns         = (known after apply)
+ arn                = (known after apply)
+ id                 = (known after apply)
+ name               = "doorway-chriscasto-srv-backend-scaling-policy-cpu"
+ policy_type        = "TargetTrackingScaling"
+ resource_id        = …
```

feat: add ecs autoscaling

---

bloom-instance/outputs.tf

Providing the right information to the app pipeline requires knowing, among other things, information about the network to run some build steps in, including the VPC ID and available subnets.  This PR adds an output to the bloom-instance project that provides these values directly for easier access.

feat: add network outputs

---

infra-pipeline/pipeline/codebuild/main.tf

The previous PR introducing the infra pipeline somehow overlooked an important component: writing to CloudWatch Logs.  Ultimately this will be covered by the pipeline module once merged and migrated, but this PR adds it in directly in the interim.

fix: add infra pipeline logging

---

modules/pipeline/main.tf

The naming patterns for notification topics in the app pipeline can create collisions with other pipelines (the infra pipeline in particular) due to the insufficient namespace used.  This PR updates the pipeline module to use the fully qualified pipeline name as the prefix instead.

fix: change notifications to use qualified name

---

app-codepipeline/ecr_repo/main.tf
app-codepipeline/ecr_repo/outputs.tf
app-codepipeline/main.tf

The app pipeline auto generates permissions for each of the repos in the configuration: one set for pulling images and another for pushing.  This makes it much easier to restrict certain pipeline actions to just being able to perform specific actions one specific repos.  This extends those permissions to also include a "retag" capability, that permits actions to add new tags to existing images.

feat: add retag perms to ecr repos

---

bloom-instance/alb/outputs.tf
bloom-instance/dns/alias/inputs.tf
bloom-instance/dns/alias/main.tf
bloom-instance/dns/alias/outputs.tf
bloom-instance/service/dns.tf
bloom-instance/service/inputs.tf

Up until now, CNAME records were used to map the desired domain names to the ALBs fronting our services.  This has worked well until recently, when it became necessary to use a domain apex record for the production public site.  It's not possible to use CNAMEs on apex records, but it is possible to use Route 53 Aliases instead.  This PR adds an alias module and modifies the service module to use that instead.

feat: use route 53 aliases

---

bloom-instance/alb/outputs.tf
bloom-instance/dns/alias/inputs.tf
bloom-instance/dns/alias/main.tf
bloom-instance/dns/alias/outputs.tf
bloom-instance/service/dns.tf
bloom-instance/service/inputs.tf
infra-pipeline/pipeline/main.tf

The output artifact for the plan file generated in the first step of each stage in the infra pipeline had a single static name.  This worked fine when it was just dev, but with staging and prod added it threw an error.  This resolves that by namespacing the output to the environment.

fix: make plan output name unique

---

bloom-instance/service/backend/locals.tf

The IAM policy used by the backend for pushing assets to S3 included a prefix component that was never used, causing the S3 ARN to be invalid.  This removes the prefix from the ARN

fix: update backend s3 policy

---

bloom-instance/logging.tf

The bucket used for storing log files has a prefix that isn't fully qualified, resulting in IAM issues and making it difficult to determine which environment it applies to.  This PR updates the prefix with the environment name to eliminate these issues

fix: change log bucket prefix

---

bloom-instance/service/backend/locals.tf

The backend service automatically populates some env vars that are either only known at apply time (like port number) with env vars passed in via the tfvars config.  Previously these were set so that the config vars are always overridden with the module-generated vars, but there are legitimate use cases for overriding some of these default values with user-provided values.  This PR separates the vars out into 3 sets of vars with different priorities (low, mid, high), and applies them in order so that some of the less important ones can have user-provided values if needed while still protecting the high priority ones from user error.

fix: update backend env var merge priorities
